/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * SceneMenu.ls
 */
export class MenuStateRTBase extends Laya.Scene {
    public Btn_start: Laya.Button;
    public ProgressBar_load: Laya.ProgressBar;
}

