/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * ScenePlay.ls
 */
export class PlayStateRTBase extends Laya.Scene {
    public Image_main: Laya.Image;
    public Image_timeEmpty: Laya.Image;
    public Image_timeBefore: Laya.Image;
    public Sprite_mask: Laya.Sprite;
    public Board: Laya.List;
    public Button_menu: Laya.Button;
    public Button_pause: Laya.Button;
    public Dialog_nextLevel: Laya.Dialog;
    public Button_nextLevel: Laya.Button;
    public FontClip_levelScore: Laya.FontClip;
    public Dialog_gameOver: Laya.Dialog;
    public Button_backHome: Laya.Button;
    public FontClip_gameScore: Laya.FontClip;
    public Box_pause: Laya.Box;
    public Box_addScore: Laya.Box;
}

